enum ActionKind {
    Walking,
    Idle,
    Jumping
}
namespace SpriteKind {
    export const Weapon = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    nav = "up"
})
function boss_attack () {
    for (let index = 0; index < 4; index++) {
        timer.after(5000, function () {
            mySprite2.follow(mySprite, 0)
            for (let index = 0; index < 4; index++) {
                projectile = sprites.createProjectileFromSprite(img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . c c c . . . . . . 
                    . . . . . . a b a a . . . . . . 
                    . . . . . c b a f c a c . . . . 
                    . . . . c b b b f f a c c . . . 
                    . . . . b b f a b b a a c . . . 
                    . . . . c b f f b a f c a . . . 
                    . . . . . c a a c b b a . . . . 
                    . . . . . . c c c c . . . . . . 
                    . . . . . . . c . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, mySprite2, 50, 50)
                projectile3 = sprites.createProjectileFromSprite(img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . c c c . . . . . . 
                    . . . . . . a b a a . . . . . . 
                    . . . . . c b a f c a c . . . . 
                    . . . . c b b b f f a c c . . . 
                    . . . . b b f a b b a a c . . . 
                    . . . . c b f f b a f c a . . . 
                    . . . . . c a a c b b a . . . . 
                    . . . . . . c c c c . . . . . . 
                    . . . . . . . c . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, mySprite2, 50, 0)
                pause(1000)
            }
            mySprite2.follow(mySprite, 20)
        })
    }
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (weapon_count > 2) {
        weapon_count = 0
    }
    AWP.destroy()
    if (weapon_count == 0) {
        AWP = sprites.create(img`
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ...............fffff..........
            .................f............
            .......fffffffffffffffffffffff
            .......f777777777777f.........
            .......f77777777fffff.........
            .......ffffffffff.............
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            `, SpriteKind.Weapon)
    } else {
        if (weapon_count == 1) {
            AWP = sprites.create(img`
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ...............f..............
                .............fff..............
                .......fffffffffffffffff......
                .......f7777777777fffff.......
                .......f77fffffffff...........
                .......ffff.ff...fff..........
                ............ff....ff..........
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                `, SpriteKind.Weapon)
        } else if (weapon_count == 2) {
            AWP = sprites.create(img`
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ..............................
                ......................f.......
                .......ffffffffffffffff.......
                .......f7777777f777777f.......
                .......f7777777f777777f.......
                .......ffffffffffffffff.......
                .................f..f.f.......
                ..................ff..........
                ..............................
                ..............................
                ..............................
                ..............................
                `, SpriteKind.Weapon)
        }
    }
    AWP.follow(mySprite, 200)
    AWP.setPosition(mySprite.x, mySprite.y)
    weapon_count += 1
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (nav == "left") {
        projectile2 = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . 3 3 3 3 3 3 3 3 3 3 3 3 . . 
            . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
            . . 3 3 3 3 3 3 3 3 3 3 3 3 . . 
            . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, mySprite, -100, 0)
    } else {
        if (nav == "right") {
            projectile2 = sprites.createProjectileFromSprite(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
                . . 3 3 3 3 3 3 3 3 3 3 3 3 . . 
                . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
                . . 1 1 1 1 1 1 1 1 1 1 1 1 . . 
                . . 3 3 3 3 3 3 3 3 3 3 3 3 . . 
                . . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, mySprite, 100, 0)
        } else {
            if (nav == "down") {
                projectile2 = sprites.createProjectileFromSprite(img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . 4 . . . . . 
                    . . . . 2 . . . . 4 4 . . . . . 
                    . . . . 2 4 . . 4 5 4 . . . . . 
                    . . . . . 2 4 d 5 5 4 . . . . . 
                    . . . . . 2 5 5 5 5 4 . . . . . 
                    . . . . . . 2 5 5 5 5 4 . . . . 
                    . . . . . . 2 5 4 2 4 4 . . . . 
                    . . . . . . 4 4 . . 2 4 4 . . . 
                    . . . . . 4 4 . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, mySprite, 0, 100)
            } else {
                if (nav == "up") {
                    projectile2 = sprites.createProjectileFromSprite(img`
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . 4 . . . . . 
                        . . . . 2 . . . . 4 4 . . . . . 
                        . . . . 2 4 . . 4 5 4 . . . . . 
                        . . . . . 2 4 d 5 5 4 . . . . . 
                        . . . . . 2 5 5 5 5 4 . . . . . 
                        . . . . . . 2 5 5 5 5 4 . . . . 
                        . . . . . . 2 5 4 2 4 4 . . . . 
                        . . . . . . 4 4 . . 2 4 4 . . . 
                        . . . . . 4 4 . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        . . . . . . . . . . . . . . . . 
                        `, mySprite, 0, -100)
                }
            }
        }
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    nav = "left"
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    nav = "right"
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    nav = "down"
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    if (nav == "left") {
        pause(100)
        mySprite3.x = mySprite3.x + -16
    } else {
        if (nav == "right") {
            pause(100)
            mySprite3.x = mySprite3.x + 16
        } else {
            if (nav == "down") {
                pause(100)
                mySprite3.y = mySprite3.y + 16
            } else {
                if (nav == "up") {
                    pause(100)
                    mySprite3.y = mySprite3.y + -16
                }
            }
        }
    }
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    statusbar.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
    statusbar.value += 1
    if (statusbar.value == statusbar.max) {
    	
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleInsignia, function (sprite, location) {
    tiles.setTileAt(location, sprites.castle.tilePath5)
    mySprite2 = sprites.create(img`
        .........................
        .........................
        .........ccccccc.........
        .........ccccccc.........
        ........c6777776cc.......
        ......cc7777777777c......
        .....c6677777777776c.....
        .....c7777c66666cc7c.....
        .....c7777c66666cc7c.....
        .....f77776ff66f667f.....
        .....f7777777777777f.....
        ....cf6677c6677777f......
        ...c77ff677cccccff.......
        ...c77ff677cccccff.......
        .cc77777fc67777277c......
        .ccc67776cfcc772777c.....
        ....c6666ccff6711111c....
        ....f66666c666111111f....
        ....f66666c666111111f....
        ....fc66666661111116f....
        .....f6666111111116f.....
        ......ffccccccccccc......
        .........................
        .........................
        .........................
        `, SpriteKind.Enemy)
    statusbar = statusbars.create(10, 4, StatusBarKind.EnemyHealth)
    statusbar.attachToSprite(mySprite2)
    statusbar.value = 10
    mySprite2.setPosition(0, 0)
    mySprite2.follow(mySprite, 20)
    animation.runImageAnimation(
    mySprite2,
    [img`
        .........................
        .........................
        .........ccccccc.........
        .........ccccccc.........
        ........c6777776c........
        ......cc777777777cc......
        .....c6677777777766c.....
        .....c7777c66666c77c.....
        .....c7777c66666c77c.....
        .....f77776f666f677f.....
        .....f7777777777777f.....
        ....cf6677c677777ff......
        ...c77ff677cccccf........
        ...c77ff677cccccf........
        .cc77777fc6777727cc......
        .ccc67776cfc7772777c.....
        ....c6666ccf66711111c....
        ....f66666c666111111f....
        ....f66666c666111111f....
        ....fc66666611111116f....
        .....f6666111111166f.....
        ......ffccccccccccc......
        .........................
        .........................
        .........................
        `,img`
        .........................
        ...........ccccccccc.....
        ...........ccccccccc.....
        ...........ccccccccc.....
        ..........c677777766c....
        .........c77777777777c...
        .......cc6777777777776c..
        .......cc777ccc66666c7c..
        .......cc777ccc66666c7c..
        .......ff777666ff6ff67f..
        .......ff7777777777777f..
        .......ff677ccc667777f...
        .......ff677ccc667777f...
        .....ccccf67777cccccf....
        .....ccccf67777cccccf....
        ....c7777ccf77777266c....
        .ccc777776fc777777776c...
        .ccccc6666c6666771111c...
        .....c666666666111111c...
        .....c666666666111111c...
        .....c666666111111116c...
        .....cc6667111111166c....
        .........................
        .........................
        .........................
        `],
    500,
    true
    )
    boss_attack()
})
let statusbar: StatusBarSprite = null
let projectile2: Sprite = null
let projectile3: Sprite = null
let projectile: Sprite = null
let mySprite2: Sprite = null
let nav = ""
let weapon_count = 0
let mySprite3: Sprite = null
let AWP: Sprite = null
let mySprite: Sprite = null
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 90, 90)
AWP = sprites.create(img`
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ...............fffff..........
    .................f............
    .......fffffffffffffffffffffff
    .......f777777777777f.........
    .......f77777777fffff.........
    .......ffffffffff.............
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    `, SpriteKind.Weapon)
scene.cameraFollowSprite(mySprite)
tiles.setCurrentTilemap(tilemap`level1`)
mySprite3 = sprites.create(img`
    . . . . . . . . b b b b b . . . 
    . . . . . . b b d d d d b b . . 
    . . . . . b d d d d d d d c . . 
    . . . . c d d d d d d d d c . . 
    . . . c b d d d d d d d b c c . 
    . . . c b b d d d d b c c c c . 
    . . c c d b b b c c c c c c c . 
    . . c c c d d d d c c d d d c c 
    . c d b c c b b c c d d d d d c 
    . c b d d b b b c c d d d d d c 
    . c c b b b b c b c b d d d b c 
    c b b c c c c c b b b b b c c c 
    c c b b c c c c c d d d d d b c 
    c c c c c c b b b b b c c c c c 
    c c c c c c c b b b b b c c c c 
    c c c c c c c c b b b b b c c c 
    `, SpriteKind.Food)
mySprite3.setPosition(100, 75)
AWP.follow(mySprite, 200)
let text_list = ["AWP", "M4", "Bazoka"]
weapon_count = 1
info.setLife(10)
controller.startLightAnimation(light.rainbowAnimation, 500)
let isBossAlive = true
